### ISSUE TITLE
MIDP模型与数据问题

### ISSUE THREAD

**Issue by xiaomi1213** [RandolphVI/Question-Difficulty-Prediction#1]
您好，
         我自己也尝试搭建过C/R/H-MIDP模型，训练数学科目的数据，在没有context时，模型的PCC能达到60%，但是使用context时却只能达到55%，我的context定义是同一张试卷，同一个学校。
         我看了您的MIDP模型（Pytorch版）的代码，但是在数据处理部分，并没有pairwise数据的生成代码，请问是否遗漏了，而且在运行您的C-MIDP(Pytorch版）的代码时，出现了UnicodeDecodeError的问题。
          我进行模型评估时是使用context分组计算PCC的，与您的代码中不同，请问论文《数据驱动的数学试题难度预测》中的模型评估是否需要分组计算PCC？

**Comment by RandolphVI** [comment]
@xiaomi1213 

非常感谢关注我们实验室的工作。这篇工作我不是作者，文章属于我的师弟，你可以发邮件询问他（wf314159@mail.ustc.edu.cn）有关PCC评价指标的问题。我复现C/R/H-MIDP模型就是练练手（目的是跑通流程即可），非属于对应文章的官方代码版本，pairwise数据生成的代码这种数据处理类的脚本不会上传（按照你对context定义自己生成pair对即可）。

祝好

**Comment by xiaomi1213** [comment]
好的，感谢您的回应。

**Comment by xiaomi1213** [comment]
您好，我已经发邮件询问您的师弟了，但是他还没有回我，能否麻烦您提醒下他回下邮件，我这边已经搞了快一个月了，context的方法始终不行，比较急，麻烦您，实在不好意思。
